# Generated by Django 3.2.6 on 2022-01-20 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_id', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Iteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteam_name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_id', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_id', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.category')),
                ('iteam', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.iteam')),
            ],
        ),
    ]
