# Generated by Django 3.2.6 on 2022-01-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iteam',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='iteam_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='rack',
            old_name='iteam',
            new_name='item',
        ),
    ]
